### ISSUE TITLE
Creating Python3 branch

### ISSUE THREAD

**Issue by joonro** [asoroa/ical2org.py#17]
Hi,

I started using Python 3 exclusively a while ago and just created a branch (https://github.com/joonro/ical2org.py/tree/python3) where the code works with python 3. I don't want to create a PR against `master` because it will break Python 2 compatibility, and I think it would be better to have a new branch for Python 3. 

May I ask you to create the branch for this? I will create a PR against the Python 3 branch once it is available in the upstream.

**Comment by asoroa** [comment]
Hi,
I've created a python3 branch and pulled your changes there.
Thanks!
