### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vlcinsky** [asoroa/ical2org.py#26]
It would be great to specify the license under which is this tool provided.

List of [throve specifiers](https://pypi.python.org/pypi?:action=list_classifiers) for python packages offer bunch of options, short list (many licenses omitted) could be as follows (first two are my favorite ones):

- OSI Approved :: MIT License
- OSI Approved :: BSD License
- OSI Approved :: GNU General Public License (GPL)
- OSI Approved :: GNU General Public License v2 (GPLv2)
- OSI Approved :: GNU General Public License v2 or later (GPLv2+)
- OSI Approved :: GNU General Public License v3 (GPLv3)
- OSI Approved :: GNU General Public License v3 or later (GPLv3+)
- OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)
- OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
- OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)
- OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)
- OSI Approved :: GNU Library or Lesser General Public License (LGPL)

For more see https://choosealicense.com/

**Comment by asoroa** [comment]
Yes, I should have done this before. My natural choice would be to choose GPL v3.
thanks for the reminder!

**Comment by vlcinsky** [comment]
Nice. GPL v3 shall work well for this kind of script (which serves mostly personal use and is not likely to become part of larger solution with commercial use).
