### ISSUE TITLE
Doesnt not import location data

### ISSUE THREAD

**Issue by matthewdeancooper** [asoroa/ical2org.py#30]
BEGIN:VEVENT
SUMMARY:INFO1113 Laboratory
DTSTART;TZID=Australia/Sydney;VALUE=DATE-TIME:20180914T140000
DTEND;TZID=Australia/Sydney;VALUE=DATE-TIME:20180914T160000
UID:****
LOCATION:SIT Lab 115
END:VEVENT

Exports as:

* INFO1113 Laboratory
  <2018-08-10 Fri 14:00>--<2018-08-10 Fri 16:00>

Really needs location information to be included next to title as:

* INFO1113 Laboratory - SIT lab 115
  <2018-08-10 Fri 14:00>--<2018-08-10 Fri 16:00>

**Comment by asoroa** [comment]
fixed, thanks for the report.
