### ISSUE TITLE
Filter out declined meetings

### ISSUE THREAD

**Issue by jpretori** [asoroa/ical2org.py#36]
My ical file (exported from Google Calendar) seems to contain all meetings, even the ones I declined (whether an individual event, or a recurring one).  ical2org.py transfers these declined events as-is into the target org file.

This causes a great deal of clutter in my org mode agenda.

I would greatly appreciate the possibility of filtering out events that I have declined.

**Comment by asoroa** [comment]
Hi,
I've created a new CLI option to manage declined events, for instance, when called like this:

`ical2orgpy -e 'a.soroa@gmail.com' -e 'a.soroa@workmail.com'
`
it will filter out events declined by me (using the emails above).
