### ISSUE TITLE
Error: 'unicode' object has no attribute 'params'

### ISSUE THREAD

**Issue by jpretori** [asoroa/ical2org.py#37]
After testing the fix to issue #36, I'm now getting this error message:

`Error: 'unicode' object has no attribute 'params'`

Beyond guessing that it might be related to line  81 (att.params), I have unfortunately no way to debug or fix it.

**Comment by asoroa** [comment]
Hi!
I cannot reproduce the issue. Can you send me the ics file (or an excerpt of it) that causes the program to fail? You can send it to me privately (to a.soroa@gmail.com) if the ics contains sensible information.
