### ISSUE TITLE
Have no default days window, i.e. parse all items by default ?

### ISSUE THREAD

**Issue by olberger** [asoroa/ical2org.py#45]
I understand that this may break stuff for some use cases, but the default which doesn't parse all elements, and applies a 90 days window seems rather surprising.

By default I would think that no filtering is done, and whenever one has performance or other issues, they may choose a particular window for specific filtering.

Of course the opposite reasoning would probably make sense ;)

Hope this helps,

**Comment by m4lvin** [comment]
I think changing the default might break [some peoples workflow](https://xkcd.com/1172/) ;-)

On the other hand, `ical2orgpy --help` should mention this, maybe change

```
  -d, --days INTEGER RANGE  Window length in days (left & right from current
                            time). Has to be positive.  [x>=0]
```

to

```
  -d, --days INTEGER RANGE  Window length in days (left & right from current
                            time). Has to be positive [x>=0], default is 90.
```

On that note, the `INTEGER RANGE` could also be misread as taking two integers, maybe just write `x` there? Or only `INTEGER`? Or am I misreading it and it is in fact possible to give different values for the left and right window length?

**Comment by asoroa** [comment]
I merged the commit from olbeger. Closing this issue.
